### PR TITLE
OAuth (Github-)Login bugfix

### PR DESCRIPTION
**Pull request by tom2796**
When using the Github OAuth login the $username variable is a int but it has to be a string, this fix converts it to a string.

### CODE REVIEW

**Comment by kingjia90** [comment]
Thank you @tom2796!

Looks ok, but what about typecasting to string here above
https://github.com/pimcore/customer-data-framework/blob/f028d4ce886814b9c1f8418c235fc08f710da38c/src/Security/UserProvider/OAuthAwareUserProvider.php#L53
and adapt the IF condition to 
`if (null === $user || "" === $username) { ` 
instead of 
`if (null === $user || null === $username) { `

since $username in `getCustomerBySsoIdentity` https://github.com/pimcore/customer-data-framework/blob/f028d4ce886814b9c1f8418c235fc08f710da38c/src/Security/UserProvider/OAuthAwareUserProvider.php#L55-L57
also expecting strings by looking in the interface
https://github.com/pimcore/customer-data-framework/blob/f028d4ce886814b9c1f8418c235fc08f710da38c/src/Security/SsoIdentity/SsoIdentityServiceInterface.php#L31-L37

It would be more future-proof as we are planning to more stricter params type

**Comment by tom2796** [comment]
Thanks for the feedback @kingjia90. 

I adapted it .

**Comment by dvesh3** [comment]
@tom2796 please remove these [lines ](https://github.com/pimcore/customer-data-framework/blob/f028d4ce886814b9c1f8418c235fc08f710da38c/phpstan-baseline.neon#L203-L206)from phpstan-baseline to fix the phpstan tests..thanks!

**Comment by tom2796** [comment]
@dvesh3 I should have fixed it now.

**Comment by kingjia90** [comment]
@tom2796  the tests are not passing, as we still have to remove that line from `phpstan-baseline.neon` because it is kind of "expecting" that error (count:1)

**Comment by dvesh3** [comment]
@tom2796 please also rebase it on 3.3 branch since it is a fix. thanks!

**Comment by dvesh3** [comment]
Closed in favor of #321

**Pull request closed without merging**
