### PR TITLE
Fix Migration error in Version20220316141955

### LINKED ISSUE #279: [Bug]: Migration error in Version20220316141955
### Expected behavior

Migrations should run without problems when updating from 3.2.7 to 3.2.8

image

### Actual behavior

```log
14:05:54 [error] Migration CustomerManagementFrameworkBundle\Migrations\PimcoreX\Version20220316141955 failed during Execution. Error: "An exception occurred while executing 'ALTER TABLE `plugin_cmf_deletions` DROP INDEX IF EXISTS `PRIMARY`;':
14:05:54 SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF EXISTS `PRIMARY`' at line 1"
14:05:54 In AbstractMySQLDriver.php line 98:

14:05:54   An exception occurred while executing 'ALTER TABLE `plugin_cmf_deletions` DROP INDEX IF EXISTS `PRIMARY`;':                                               
14:05:54   SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF EXISTS `PRIMARY`' at line 1      
```

### Steps to reproduce

Update from 3.2.7 to 3.2.8 on AWS MySQL 8.0

### PR DESCRIPTION
**Pull request by dvesh3**
Resolves #279

### CODE REVIEW

**Comment by dvesh3** [comment]
@NiklasBr could you please test it? thanks!

**Comment by NiklasBr** [comment]
@dvesh3 This did not fix the error, but note the logs that it appeared in
`CustomerManagementFrameworkBundle\Migrations\PimcoreX\Version20220316141955`
and not in
`CustomerManagementFrameworkBundle\Migrations\Version20220316141955`

**Comment by dvesh3** [comment]
> @dvesh3 This did not fix the error, but note the logs that it appeared in `CustomerManagementFrameworkBundle\Migrations\PimcoreX\Version20220316141955` and not in `CustomerManagementFrameworkBundle\Migrations\Version20220316141955`

@NiklasBr yes, i missed the Pimcore X migration. It should be fixed now.

**Comment by NiklasBr** [comment]
That worked 👍

**Pull request merged**
