### PR TITLE
Fixed installer not adding stored functions issue

### LINKED ISSUE #402: [Bug]: SQLSTATE[42000]: Syntax error or access violation: 1305 FUNCTION db.PLUGIN_CMF_COLLECT_OBJECT_SEGMENT_ASSIGNMENTS does not exist
### Expected behavior

After a fresh installation of Pimcore and CMF and enabled the packagea and created a Customer Data Object, update the configuration files should be everything ok (no data just Class definitions)

Environment (Docker):

- Pimcore 10.5.15
- Symfony: 5.4.18

### Actual behavior

Error in Pimcore Admin 

```
Timestamp: Fri Jan 20 2023 12:08:23 GMT+0300 (GMT+03:00)
Status: 500 | Internal Server Error
URL: /admin/customermanagementframework/segment-assignment/inheritable-segments?id=2&type=object&_dc=1674205703397
Method: GET
Message: An exception occurred while executing 'SELECT PLUGIN_CMF_COLLECT_OBJECT_SEGMENT_ASSIGNMENTS(?)' with params ["1"]:

SQLSTATE[42000]: Syntax error or access violation: 1305 FUNCTION db.PLUGIN_CMF_COLLECT_OBJECT_SEGMENT_ASSIGNMENTS does not exist
```

### Steps to reproduce

Pimcore Admin with no Exceptions or errors

### PR DESCRIPTION
**Pull request by aashan10**
Resolves #402

### CODE REVIEW

**Comment by dvesh3** [comment]
Closing it as the reported issue is not reproducible.

**Comment by HageMaster3108** [comment]
@dvesh3 See issue #402 - the issue IS clearly reproducable!

**Comment by dvesh3** [comment]
Hi @aashan10 I looked deeper into https://github.com/pimcore/pimcore/issues/4526 which led to introduction of delimiter in .sql scripts (basically for running them manually on command line) but this breaks installer scripts now. The installer runs now with your changes but again you won't be able to execute these scripts manually on command line without delimiters. I would suggest that we add a section in [installation docs](https://pimcore.com/docs/customer-management-framework/current/Installation/index.html) for manually executing stored function scripts with delimiter, if the execution fails somehow on installation. wdyt?

**Comment by dvesh3** [comment]
Docs added here https://github.com/pimcore/customer-data-framework/commit/5aa8ccf1cae9885c266b74623f2d446df312fbf4

**Pull request merged**
