### PR TITLE
fixed enqueue children for type asset

### PR DESCRIPTION
**Pull request by MercuryKojo**
the asset table does not have a "key" row. It uses "filename"

### CODE REVIEW

**Comment by fashxp** [comment]
thank you very much for your PR. can you please sign the CLA so that we can merge?

**Comment by MercuryKojo** [comment]
> thank you very much for your PR. can you please sign the CLA so that we can merge?

Sorry, thought I had already done that, but it was only for pimcore itself

**Comment by blankse** [comment]
@fashxp Is only merged on master. So the milestone is incorrect.

**Comment by fashxp** [comment]
you're right. thx.

**Pull request merged**
