### PR TITLE
PHP 8.3 Support

### PR DESCRIPTION
**Pull request by blankse**
See https://github.com/pimcore/pimcore/pull/16589

Requires https://github.com/pimcore/personalization-bundle/pull/66

### CODE REVIEW

**Comment by limenet** [comment]
@blankse since https://github.com/pimcore/personalization-bundle/pull/66 and https://github.com/pimcore/pimcore/pull/16589 are merged, what's needed to get this merged as well?

**Comment by blankse** [comment]
@limenet The 1.1.0 release in `pimcore/personalization-bundle`, because the tests only loads releases.

**Comment by kingjia90** [comment]
@blankse could you please temporary change to require the `1.x-dev` branch of personalization bundle to let the test run again? 
I am confident that it would be green but just to be sure 😄 Then i will just merge this, i am then also proceeding on merging https://github.com/pimcore/demo/pull/568 which led me here

**Comment by blankse** [comment]
@kingjia90 This is not enough for the demo repository. You also need https://github.com/pimcore/ecommerce-framework-bundle/pull/164 https://github.com/pimcore/data-hub/pull/840

**Comment by kingjia90** [comment]
Ahh right, then it's worth to merge and test near the minor releases day otherwise the master branch would be still reporting false negative tests, it shouldn't take that much time by then, thank you anyways

**Comment by fashxp** [comment]
@blankse you are simply too fast ;-) 
thx for fixing.

**Pull request merged**
