### PR TITLE
[Task] Add pimcore 10 and 11 support for new menu creation

### LINKED ISSUE #403: [Improvement]: Adjust navigation creation
### Improvement description

Moving all code for the navigation creation to the pimcoreReady function to stay compatible with the new menu creation approach in Pimcore 11. Use the new approach based on the preMenuBuild Event

Based on https://github.com/pimcore/pimcore/pull/14113

### PR DESCRIPTION
**Pull request by mattamon**
## Changes in this pull request  
Resolves #403 

## Additional info  
If new preMenuBuild Event is available use the new methods, if not use the pimcoreReady Event to setup the menu

### CODE REVIEW

**Comment by kingjia90** [comment]
I am wondering if we could futher break down and extract menu items to avoid duplicate fragments, at the moment `initToolbar` and `initMenu` are quite similar.
https://www.diffchecker.com/ItcLvg3w/

What i want to avoid is that whenever one change something,  would always have to apply changes to the other method, but at the same time, it mustn't limit 11 potential improvemenents.

**Comment by mattamon** [comment]
I'm going to take a look into that. I think the main part is how the menu is added, so I could basically make proper functions to get the menus and then in initToolbar add them the old way and in initMenu, use the new approach.

**Comment by mattamon** [comment]
I restructured it like I said above. It is still not the nicest way, but much better than before. I think changing it more, would only make it more complicated.

**Comment by kingjia90** [comment]
Looks much better but currently the items in `initMenu` do not make the most of the `priority` field (adding this property, shouldn't affect the old approach) and wondering if it would be worth  to change from 
```
let somevar = somefunc;
if (somevar){
   array.push(somevar);
}
```
to just `array.push(somefunc);` and clean the `null` values (since they can return null) at the end of the function or just before `menu.cmf`

**Comment by mattamon** [comment]
Since it is it's own menu, and we do not set the priority anywhere, the priority gets set automatically. I would change this approach tbh because the result would be the same as before, right?

Just pushing the function seems legit, but we would have a problem with the customerMenu, itself. If there are no changes for the submenu, then pushing the function is okay, but I would rather go for the a consistent approach. Wdyt?

**Comment by kingjia90** [comment]
> Since it is it's own menu, and we do not set the priority anywhere, the priority gets set automatically. I would change this approach tbh because the result would be the same as before, right?
> 
> Just pushing the function seems legit, but we would have a problem with the customerMenu, itself. If there are no changes for the submenu, then pushing the function is okay, but I would rather go for the a consistent approach. Wdyt?

ah ok, nice points, then let's keep it this way. 
Just one minor "code style" fix (blue/green lines in the screenshot), there's a break line between the `let` an the `if`
image

and should be good to be merged

**Pull request merged**
