### PR TITLE
Revert "Add primary key to plugin_cmf_deletions table"

### PR DESCRIPTION
**Pull request by dvesh3**
Reverts pimcore/customer-data-framework#252

Resolves https://github.com/pimcore/customer-data-framework/issues/273

## Additional Information
As this breaks existing implementations with multiple entries having same `id`+`entityType` in `plugin_cmf_deletions`

### CODE REVIEW

**Comment by blankse** [comment]
@dvesh3 Than we should use only a insert method and not insertAndUpdate to save this entries.

**Comment by dvesh3** [comment]
@blankse I would keep it as and add autoincrement id to the table.

**Comment by dvesh3** [comment]
@blankse I would keep it as and add autoincrement id to the table.

**Comment by blankse** [comment]
@dvesh3 If you create this autoincrement id column, consider that someone has this primary key and someone haven't.

**Comment by dvesh3** [comment]
@blankse do you have a better idea?

**Comment by blankse** [comment]
@dvesh3 No its good. But we must remove this primary key before we add a new one. Only remove the migration doesn't remove the primary key again.

**Comment by dvesh3** [comment]
@blankse there you go https://github.com/pimcore/customer-data-framework/commit/6069d19e4c4c4592a490f1504d16d4d6feb36d22

**Comment by blankse** [comment]
@dvesh3 👍🏼

**Pull request merged**
