### PR TITLE
Made input filter as a default wildcard filter

### LINKED ISSUE #234: [Improvement]: Make input filter auto wildcard (*input*)
### Improvement description

Hello,

Purpose of this issue is to improve the enduser experience on the search panel for customer.
Actually, it only send exact text. To search for instance for lastname begining with, we need to add a wildcard (*) at the end.

Exemple on the Pimcore demo :
- without * :

image

- with * :

image

I think it would be better for user experience that automatic wildcard is added without the need to write it on the input. It could be added on email, lastname, firstname fields as well the search input field. For user not technical it wil be better.

If this way not possible, adding at least this * possibility of operator in the help so user know he can use this operator:

image

Thanks.

### PR DESCRIPTION
**Pull request by aryaantony92**
Resolves #234

### CODE REVIEW

**Comment by kingjia90** [comment]
It kind of works, but there are cases where it doesn't work

`Din OR Fre` returns only `Fred`, maybe as it only appends the wildcard at the end of the string (expecting also DIno)

Also casually found a bug, if you search `"Fred"` it returns nothing because the doublequotes get escaped into `'\"Fred\"'`,  so it doesn't match the instruction about the  `exact search modifier`
image

Likely due to `$listing->quote($this->query)` on line 62
https://github.com/pimcore/customer-data-framework/blob/edfdd386697bd67d51e5a4ccfd028e23657dbd21/src/CustomerList/Filter/SearchQuery.php#L59-L63

I would suggest to do some rework in that snippet, it might clear both issues in one time.
My first though would be to kind of "invert" this IF block, in other words, IF double quotes are found use the `%s = %s`, ELSEIF found `*` replace it with `%` in the specificied position, ELSE, surround everything with `%`.

**Comment by aryaantony92** [comment]
@kingjia90 Could you please try searching with "Fred" once more ? It's working for me.

**Comment by kingjia90** [comment]
image
@aryaantony92 still doesn't work for me

**Comment by aryaantony92** [comment]
@kingjia90 Sorry, I was talking about the search bar.

**Pull request closed without merging**
