### PR TITLE
Cast querybuilder to string when fetching data

### LINKED ISSUE #216: 0 1 Serialization of 'Doctrine\DBAL\Driver\PDO\Connection' is not allowed
ERROR WITH CREATING NEW CUSTOMER -> ACTIVITIES TAB

I have installed PIMCORE-10
I created a new Class Customer : (copy of)
https://github.com/pimcore/customer-data-framework/blob/master/install/class_source/optional/class_Customer_export.json

ERROR 1)
Serialization of 'Doctrine\DBAL\Driver\PDO\Connection' is not allowed
ExceptionLogs 2Stack Trace
Exception
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Profiler/FileProfilerStorage.php (line 175)
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Profiler/FileProfilerStorage.php serialize (line 175)
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Profiler/Profiler.php -> write (line 101)
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/ProfilerListener.php -> saveProfile (line 112)
in vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php -> onKernelTerminate (line 117)
in vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php -> __invoke (line 230)
in vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php -> callListeners (line 59)
in vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php -> dispatch (line 151)
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php -> dispatch (line 99)
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php -> terminate (line 152)
Kernel->terminate()
in public/index.php (line 38)
Tool::setCurrentRequest(null);$response = $kernel->handle($request);$response->send();$kernel->terminate($request, $response);

ERROR 2)
Symfony\Component\VarDumper\Cloner\Data objects are immutable.
BadMethodCallException
in /opt/pimcore/vendor/symfony/symfony/src/Symfony/Component/VarDumper/Cloner/Data.php (line 165)
return $this->__get($key); } public function offsetSet($key, $value) { throw new \BadMethodCallException(self::class.' objects are immutable.'); } public function offsetUnset($key) { throw new \BadMethodCallException(self::class.' objects are immutable.');
in /opt/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DataCollector/EventDataCollector.php -> offsetSet (line 82)
* * @see TraceableEventDispatcher / public function setCalledListeners(array $listeners) { $this->data['called_listeners'] = $listeners; } /* * Gets the called listeners. *
in /opt/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DataCollector/EventDataCollector.php -> setCalledListeners (line 65)
} public function lateCollect() { if ($this->dispatcher instanceof TraceableEventDispatcher) { $this->setCalledListeners($this->dispatcher->getCalledListeners($this->currentRequest)); $this->setNotCalledListeners($this->dispatcher->getNotCalledListeners($this->currentRequest)); $this->setOrphanedEvents($this->dispatcher->getOrphanedEvents($this->currentRequest)); } $this->data = $this->cloneVar($this->data);
in /opt/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Profiler/Profiler.php -> lateCollect (line 97)
public function saveProfile(Profile $profile) { // late collect foreach ($profile->getCollectors() as $collector) { if ($collector instanceof LateDataCollectorInterface) { $collector->lateCollect(); } } if (!($ret = $this->storage->write($profile)) && null !== $this->logger) { $this->logger->warning('Unable to store the profiler information.', ['configured_storage' => \get_class($this->storage)]);
in /opt/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/ProfilerListener.php -> saveProfile (line 112)
} } // save profiles foreach ($this->profiles as $request) { $this->profiler->saveProfile($this->profiles[$request]); } $this->profiles = new \SplObjectStorage(); $this->parents = new \SplObjectStorage(); }
in /opt/pimcore/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php -> onKernelTerminate (line 117)
$this->called = true; $this->priority = $dispatcher->getListenerPriority($eventName, $this->listener); $e = $this->stopwatch->start($this->name, 'event_listener'); ($this->optimizedListener ?? $this->listener)($event, $eventName, $dispatcher); if ($e->isStarted()) { $e->stop(); }
in /opt/pimcore/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php -> __invoke (line 230)
foreach ($listeners as $listener) { if ($stoppable && $event->isPropagationStopped()) { break; } $listener($event, $eventName, $this); } } /** * Sorts the internal list of listeners for the given event by priority.
in /opt/pimcore/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php -> callListeners (line 59)
} else { $listeners = $this->getListeners($eventName); } if ($listeners) { $this->callListeners($listeners, $eventName, $event); } return $event; }
in /opt/pimcore/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php -> dispatch (line 151)
try { $this->beforeDispatch($eventName, $event); try { $e = $this->stopwatch->start($eventName, 'section'); try { $this->dispatcher->dispatch($event, $eventName); } finally { if ($e->isStarted()) { $e->stop(); } }
in /opt/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php -> dispatch (line 99)
/** * {@inheritdoc} / public function terminate(Request $request, Response $response) { $this->dispatcher->dispatch(new TerminateEvent($this, $request, $response), KernelEvents::TERMINATE); } /* * @internal /
in /opt/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php -> terminate (line 116)
$response = $this->handleThrowable($exception, $request, self::MASTER_REQUEST); $response->sendHeaders(); $response->sendContent(); $this->terminate($request, $response); } /* * Handles a request to convert it to a response. *
in /opt/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/DebugHandlersListener.php -> terminateWithException (line 127)
in /opt/pimcore/vendor/symfony/symfony/src/Symfony/Component/ErrorHandler/ErrorHandler.php :: Symfony\Component\HttpKernel\EventListener{closure} (line 607)
ErrorHandler->handleException()

### PR DESCRIPTION
**Pull request by fashxp**
fixed #216

### CODE REVIEW

**Comment by ismetsener** [comment]
thanks it helped, but now I get the message:
Class name must be a valid object or a string

**Comment by fashxp** [comment]
Do you have more information, call stack etc?

**Comment by ismetsener** [comment]
Do you have more information, call stack etc?
what kind of information shall I sent you?

**Comment by ismetsener** [comment]
Class name must be a valid object or a string
Error:
Class name must be a valid object or a string

  at /opt/pimcore/vendor/sensio/framework-extra-bundle/src/Request/ParamConverter/ParamConverterManager.php:62
  at Sensio\Bundle\FrameworkExtraBundle\Request\ParamConverter\ParamConverterManager->applyConverter()
     (/opt/pimcore/vendor/sensio/framework-extra-bundle/src/Request/ParamConverter/ParamConverterManager.php:48)
  at Sensio\Bundle\FrameworkExtraBundle\Request\ParamConverter\ParamConverterManager->apply()
     (/opt/pimcore/vendor/sensio/framework-extra-bundle/src/EventListener/ParamConverterListener.php:72)
  at Sensio\Bundle\FrameworkExtraBundle\EventListener\ParamConverterListener->onKernelController()
     (/opt/pimcore/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php:117)
  at Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke()
     (/opt/pimcore/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:230)
  at Symfony\Component\EventDispatcher\EventDispatcher->callListeners()
     (/opt/pimcore/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:59)
  at Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
     (/opt/pimcore/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php:151)
  at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch()
     (/opt/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:145)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
     (/opt/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:79)
  at Symfony\Component\HttpKernel\HttpKernel->handle()
     (/opt/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/ErrorListener.php:60)
  at Symfony\Component\HttpKernel\EventListener\ErrorListener->onKernelException()
     (/opt/pimcore/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php:117)
  at Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke()
     (/opt/pimcore/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:230)
  at Symfony\Component\EventDispatcher\EventDispatcher->callListeners()
     (/opt/pimcore/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:59)
  at Symfony\Component\EventDispatcher\EventDispatcher->dispatch()
     (/opt/pimcore/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php:151)
  at Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch()
     (/opt/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:218)
  at Symfony\Component\HttpKernel\HttpKernel->handleThrowable()
     (/opt/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:111)
  at Symfony\Component\HttpKernel\HttpKernel->terminateWithException()
     (/opt/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/DebugHandlersListener.php:127)
  at Symfony\Component\HttpKernel\EventListener\DebugHandlersListener::Symfony\Component\HttpKernel\EventListener\{closure}()
     (/opt/pimcore/vendor/symfony/symfony/src/Symfony/Component/ErrorHandler/ErrorHandler.php:607)
  at Symfony\Component\ErrorHandler\ErrorHandler->handleException()

**Comment by fashxp** [comment]
Steps to reproduce?

**Comment by ismetsener** [comment]
Dear Christian,

It is a fresh installation  pimcore/skeleton  where I created a customer
I have also a pimcore/demo installation with existing customer
where I get the same error

**Comment by fashxp** [comment]
But what do you do to get this error? 
Open what page, calling what action?

**Comment by ismetsener** [comment]
error returned back:
error:  Serialization of 'Doctrine\DBAL\Driver\PDO\Connection' is not allowed
after update 
error:Class name must be a valid object or a string
now
error: Serialization of 'Doctrine\DBAL\Driver\PDO\Connection' is not allowed

**Comment by fashxp** [comment]
Sorry, as long as you don't describe exact steps to reproduce the error, it is really hard to find them ...

**Comment by ismetsener** [comment]
step1) I installed CMF: composer require  pimcore/customer-management-framework-bundlecreated a new customer
step2) create a customer, save and reloaded
step3) go to  Activities tab, here I see the errors:
error1: Serialization of 'Doctrine\DBAL\Driver\PDO\Connection' is not allowed
error2: Symfony\Component\VarDumper\Cloner\Data objects are immutable.


I got the same error: https://demo.pimcore.fun/admin/?_dc=1621284110&perspective=

**Comment by fashxp** [comment]
sorry, cannot reproduce your problems anymore with the fix of this PR. 
https://demo.pimcore.fun/admin does not have the fix yet as it is not merged and released

**Pull request merged**
