### PR TITLE
Added null check to confirm (new) customer objects have an id before use.

### PR DESCRIPTION
**Pull request by keifphos**
Added null check to confirm (new) customer objects have an id before attempting to use the id as per #517

### CODE REVIEW

**Comment by robertSt7** [comment]
Hi @keifphos since this is a bug fix could you please rebase the PR to 4.0? Thanks

**Comment by keifphos** [comment]
Hey @robertSt7 no worries that is done, thanks.

**Comment by robertSt7** [comment]
@keifphos There are still other commits besides yours in the PR. Could you please drop these commits and force push or open a new PR with 4.0 as base? Thank you

**Comment by keifphos** [comment]
@robertSt7 my bad, i'll close this and make a new PR.

**Pull request closed without merging**
