### PR TITLE
Fix: Not setting the attribute "package" of the "deprecated" option is deprecated.

### PR DESCRIPTION
**Pull request by blankse**

### CODE REVIEW

**Comment by blankse** [comment]
Deprecation warning can probably only be fixed when we drop Pimcore 6.9 support...

**Comment by dvesh3** [comment]
@blankse Is it done from your side?

**Comment by blankse** [comment]
@dvesh3 When we can drop Pimcore 6.9 support: Yes. It's only possible in Symfony 5

**Comment by blankse** [comment]
I rebased it. Should be ready now.

**Comment by kingjia90** [comment]
Could you please also add the fix for these 2 deprecations that were introduced afterwards so that the fixes would appear all under the same PR? 

introduced in #281
https://github.com/pimcore/customer-data-framework/blob/76684d9c3471e556c61b2337d2b29a8b4f8c133a/src/Resources/config/services_security.yml#L27
introduced in #294
https://github.com/pimcore/customer-data-framework/blob/76684d9c3471e556c61b2337d2b29a8b4f8c133a/src/Resources/config/services_security_webservice_legacy.yml#L13
Thank you in advance

**Comment by blankse** [comment]
@kingjia90 I changed also the 2 new deprecations.

**Pull request merged**
