### PR TITLE
Add MySQL compatibility

### PR DESCRIPTION
**Pull request by BlackbitNeueMedien**
This PR provides JSON support to store activity data instead of MariaDB's dynamic columns. Whether MySQL or MariaDB shall be used can be configured in services.yml (change CustomerManagementFrameworkBundle\ActivityStore\ActivityStoreInterface to CustomerManagementFrameworkBundle\ActivityStore\MySQL). 
For compatibility reasons it does not use JSON column type but keeps database structure untouched.

Solves #58

### CODE REVIEW

**Comment by markus-moser** [comment]
Great, thank you!

We will take a look at it in detail. 

One question: if we do not change the database structure the mysql JSON search/filter possibilities will not work, correct? Wouldn't it be better to create a new/separate table for the mysql store which supports the JSON datatype?

**Comment by BlackbitNeueMedien** [comment]
I am not sure which functionality you exactly mean. Could you point me to the code in the current master branch? Then I could look for the pendant in this PR (or say if it is missing).

**Comment by markus-moser** [comment]
This functionality is not directly used within the bundle itself but could be used for example by segment builders (or other tools) to filter the activities table based on attributes within the "attributes" column.

For example:
```
WHERE COLUMN_GET(attributes, 'myAttribute' AS CHAR) = 'value xyz';
```

The JSON datatype supports similiar functionallities:
https://dev.mysql.com/doc/refman/5.7/en/json-search-functions.html

But I think this will only work if it is actually a JSON field.

**Comment by BlackbitNeueMedien** [comment]
Yes, with the current database structure you can use `CAST(column AS JSON)` (see https://dev.mysql.com/doc/refman/8.0/en/json.html#json-converting-between-types) and then you are able to filter. Of course this would not be the best solution regarding performance but we have to decide which minimum MySQL version we want to support. If 5.7 is acceptable then it certainly makes sense to use a separate datastore for MySQL.

**Comment by fashxp** [comment]
from my point of view 5.7 would be fine ... since aws aurora also supports 5.7

**Comment by Cruiser13** [comment]
@fashxp any chance to merge this so we can use MySQL instead of MariaDB with the customer data framework?

**Comment by fashxp** [comment]
we discussed our next steps internally. 
we're going to merge this PR in order to support mysql < 5.7
in addition we would like to create an additional activity store that supports the JSON data type of mysql (since now both, mysql and mariadb support this one).

**Comment by fashxp** [comment]
@BlackbitNeueMedien  are you done and have you tested the mysql store? did you also regression-test the mariadb store?

**Comment by BlackbitNeueMedien** [comment]
Yes, we run this fork on 2 productive projects and have not noticed any problems.

**Comment by Cruiser13** [comment]
@fashxp can this be merged with the next cmf release?

**Pull request merged**
