### PR TITLE
Upgraded to PHP CS Fixer v3

### PR DESCRIPTION
**Pull request by blankse**
See other pimcore repositories

### CODE REVIEW

**Comment by blankse** [comment]
PhpStan is fixed by https://github.com/pimcore/customer-data-framework/pull/533

**Comment by blankse** [comment]
Merged the 4.0 branch to fix the php stan errors here

**Comment by markus-moser** [comment]
@blankse 
Thanks a lot! I would prefer if we execute the github workflows also for PRs like here: https://github.com/pimcore/opensearch-client/blob/1.x/.github/workflows/php-cs-fixer.yaml#L4

With this the CS fixer changes would be handled in the PR and for example in this one we could directly see the changes. When merging a PR we could then squash it and would have a clean commit history. WDYT?

**Comment by blankse** [comment]
@markus-moser I would also prefer this. Did you test it with pull requests from forks? It seems not to work. The `github-actions bot` doesn't have permission to write in my repository. I checked the "Allow edits and access to secrets by maintainers" checkbox:
`Permission to blankse/customer-data-framework.git denied to github-actions[bot].`

See: https://github.com/pimcore/customer-data-framework/actions/runs/8862166212/job/24334805955?pr=532

**Comment by blankse** [comment]
Might work now.

The changes are from: https://github.com/stefanzweifel/git-auto-commit-action?tab=readme-ov-file#workflow-should-run-in-base-repository

See also: https://github.com/stefanzweifel/git-auto-commit-action/issues/211

**Comment by markus-moser** [comment]
@blankse Oh, sorry, no I never tested it with forks. Thank you very much for figuring this tricky thing out, let's give it a try 👍

**Comment by markus-moser** [comment]
@blankse Thanks again - seems to work fine 👍 (see #536)

I'll discuss it with the team if we should make this our default behaviour for our bundles.

**Pull request merged**
